name: Daily INTL Sports Risk (Slack only)

on:
  schedule:
    - cron: "0 9 * * *"   # daily at 09:00 UTC
  workflow_dispatch:       # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run daily report (ESPN scrape → Slack)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Tuning knobs — adjust as you like
          SCAN_DAYS: "30"              # look ahead window
          DISPLAY_TZ: "America/New_York"
          HIGH_CUTOFF: "55"            # lower = more “High” alerts
          MEDIUM_CUTOFF: "40"
          TOP_N: "15"                  # max items listed in Slack preview
        run: python src/main.py
